"""migrate configuration

Revision ID: fd054861f049
Revises: 
Create Date: 2022-04-25 10:38:54.444975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd054861f049'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'student', ['studentemail'])
    op.create_unique_constraint(None, 'student', ['studentusername'])
    op.create_unique_constraint(None, 'teacher', ['teachemail'])
    op.create_unique_constraint(None, 'teacher', ['teachusername'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'teacher', type_='unique')
    op.drop_constraint(None, 'teacher', type_='unique')
    op.drop_constraint(None, 'student', type_='unique')
    op.drop_constraint(None, 'student', type_='unique')
    # ### end Alembic commands ###
